builds:
  - env:
    - CGO_ENABLED=0
    binary: yp-server
    main: ./
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binary: yp-server
    image: innovate/yp-server
    skip_push: false
    dockerfile: Dockerfile
    # Template of the docker tag. Defaults to `{{ .Version }}`.
    # Other allowed fields are:
    # - `.Commint`
    # - `.Tag`
    # - `.Major`
    # - `.Minor`
    # - `.Patch`
    # - `.Env.VARIABLE_NAME`
    tag_templates:
    - "amd64-{{ .Tag }}"
    - "amd64-v{{ .Major }}"
    - amd64-latest
  - goos: linux
    goarch: arm64
    goarm: ''
    binary: yp-server
    image: innovate/yp-yp-server
    skip_push: false
    dockerfile: Dockerfile
    # Template of the docker tag. Defaults to `{{ .Version }}`.
    # Other allowed fields are:
    # - `.Commint`
    # - `.Tag`
    # - `.Major`
    # - `.Minor`
    # - `.Patch`
    # - `.Env.VARIABLE_NAME`
    tag_templates:
    - "arm64-{{ .Tag }}"
    - "arm64-v{{ .Major }}"
    - arm64-latest
  - goos: linux
    goarch: arm
    goarm: '6'
    binary: yp-server
    image: innovate/yp-yp-server
    skip_push: false
    dockerfile: Dockerfile
    # Template of the docker tag. Defaults to `{{ .Version }}`.
    # Other allowed fields are:
    # - `.Commint`
    # - `.Tag`
    # - `.Major`
    # - `.Minor`
    # - `.Patch`
    # - `.Env.VARIABLE_NAME`
    tag_templates:
    - "armhf-{{ .Tag }}"
    - "armhf-v{{ .Major }}"
    - armhf-latest