language: go
dist: xenial
go: "1.x.x"

env:
    global:
      - DOCKER_REPO=innovate/yp-server

stages:
- name: test
- name: release
  if: tag IS present

jobs:
  include:
  - stage: test
    name: Go Tests
    language: go
  - stage: release
    name: "Release"
    script: curl -sL https://git.io/goreleaser | bash
  - stage: release
    name: "Release to production"
    script: 
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_REPO:$TRAVIS_TAG ./
      - docker push $DOCKER_REPO:$TRAVIS_TAG
      - docker tag $DOCKER_REPO:$TRAVIS_TAG $DOCKER_REPO:latest; docker push $DOCKER_REPO:latest;
      - HELM_VERSION=v2.9.1 B64_CA_CRT=$B64_CA_CRT SERVICE_ACCOUNT_TOKEN=$SERVICE_ACCOUNT_TOKEN CLUSTER_ENDPOINT=$CLUSTER_ENDPOINT HELM_RELEASE=yp-server HELM_CHART="./chart" K8S_NAMESPACE=yp-server HELM_ARGS="--set image.tag=$TRAVIS_COMMIT" make deploy